/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.cajv.telas;

import java.sql.*;
import br.com.cajv.dal.ModuloConexao;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author islan
 */
public class TelaVsgFun extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form TelaVsgFun
     */
    public TelaVsgFun() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    private void consultarId(){
        String sql = "select * from funcionarios where idfunc = ?";
        int setar = tblVsgFun.getSelectedRow();
        txtVsgFunId.setText(tblVsgFun.getModel().getValueAt(setar, 0).toString());
        txtVsgFunNom.setText(tblVsgFun.getModel().getValueAt(setar, 1).toString());
        cboVsgFunCar.setSelectedItem(tblVsgFun.getModel().getValueAt(setar, 2).toString());
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,tblVsgFun.getModel().getValueAt(setar, 0).toString());
            rs=pst.executeQuery();
            if (rs.next()) {
                txtVsgFunFon.setText(rs.getString(4));
                txtVsgFunDen.setText(rs.getString(6));
                txtVsgFunDsa.setText(rs.getString(7));
                txtVsgFunCep.setText(rs.getString(8));
                txtVsgFunEnd.setText(rs.getString(9));
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não cadastrado.");
                txtVsgFunId.setText(null);
                txtVsgFunNom.setText(null);
                cboVsgFunCar.setSelectedItem(1);
                txtVsgFunFon.setText(null);
                txtVsgFunDen.setText(null);
                txtVsgFunDsa.setText(null);
                txtVsgFunCep.setText(null);
                txtVsgFunEnd.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void consultaNome(){
        String sql = "select idfunc,nomefunc,cargo from funcionarios where nomefunc like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,txtVsgFunPesNom.getText()+"%");
            rs=pst.executeQuery();
            // biblioteca rs2xml.jar;
            tblVsgFun.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void consultaCargo(){
        String sql = "select idfunc,nomefunc,cargo from funcionarios where cargo = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,cboVsgFunPesCar.getSelectedItem().toString());
            rs=pst.executeQuery();
            // biblioteca rs2xml.jar;
            tblVsgFun.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void redefinir(){
        String sql = "select idfunc,nomefunc,cargo from funcionarios";
        try {
            pst = conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            // biblioteca rs2xml.jar;
            tblVsgFun.setModel(DbUtils.resultSetToTableModel(rs));
            txtVsgFunId.setText(null);
            txtVsgFunNom.setText(null);
            cboVsgFunCar.setSelectedItem(1);
            txtVsgFunFon.setText(null);
            txtVsgFunDen.setText(null);
            txtVsgFunDsa.setText(null);
            txtVsgFunCep.setText(null);
            txtVsgFunEnd.setText(null);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVsgFunNom1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVsgFunPesNom = new javax.swing.JTextField();
        cboVsgFunPesCar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVsgFun = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnVsgFunRed = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtVsgFunId = new javax.swing.JTextField();
        txtVsgFunNom = new javax.swing.JTextField();
        txtVsgFunFon = new javax.swing.JTextField();
        txtVsgFunDen = new javax.swing.JTextField();
        txtVsgFunDsa = new javax.swing.JTextField();
        txtVsgFunCep = new javax.swing.JTextField();
        txtVsgFunEnd = new javax.swing.JTextField();
        cboVsgFunCar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        btnVsgFunNom1.setText("🔎");
        btnVsgFunNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVsgFunNom1ActionPerformed(evt);
            }
        });

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cajv/icones/iconCajV.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(734, 460));
        setMinimumSize(new java.awt.Dimension(734, 460));

        jLabel2.setText("Pesquisa por nome");

        jLabel3.setText("Pesquisa por cargo");

        txtVsgFunPesNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVsgFunPesNomActionPerformed(evt);
            }
        });
        txtVsgFunPesNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVsgFunPesNomKeyReleased(evt);
            }
        });

        cboVsgFunPesCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RH", "Gerente de loja", "Coordenador", "Segurança", "Fiscal de caixa", "Operador de caixa", "Repositores", "Serviços gerais", "Estagiário" }));
        cboVsgFunPesCar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVsgFunPesCarItemStateChanged(evt);
            }
        });

        tblVsgFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "CARGO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVsgFun.setEditingColumn(0);
        tblVsgFun.setEditingRow(0);
        tblVsgFun.setName("Funcionários"); // NOI18N
        tblVsgFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVsgFunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVsgFun);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Redefinir Tabela");

        btnVsgFunRed.setText("❌");
        btnVsgFunRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVsgFunRedActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dados do funcionário");

        jLabel6.setText("ID");

        jLabel7.setText("Nome");

        jLabel8.setText("Cargo");

        jLabel9.setText("Fone");

        jLabel11.setText("D. entrada");

        jLabel12.setText("D. saída");

        jLabel13.setText("CEP");

        jLabel14.setText("Endereço");

        txtVsgFunId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVsgFunIdKeyReleased(evt);
            }
        });

        cboVsgFunCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RH", "Gerente de loja", "Coordenador", "Segurança", "Fiscal de caixa", "Operador de caixa", "Repositores", "Serviços gerais", "Estagiário" }));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Funcionários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVsgFunPesNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboVsgFunPesCar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 184, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVsgFunRed, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVsgFunFon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVsgFunId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboVsgFunCar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVsgFunNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVsgFunCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVsgFunDsa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVsgFunDen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVsgFunEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVsgFunRed))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboVsgFunPesCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVsgFunPesNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cboVsgFunCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtVsgFunFon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunDsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVsgFunEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVsgFunPesNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVsgFunPesNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsgFunPesNomActionPerformed

    private void btnVsgFunRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVsgFunRedActionPerformed
        // TODO add your handling code here:
        redefinir();
    }//GEN-LAST:event_btnVsgFunRedActionPerformed

    private void btnVsgFunNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVsgFunNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVsgFunNom1ActionPerformed

    private void txtVsgFunPesNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVsgFunPesNomKeyReleased
        // TODO add your handling code here:
        consultaNome();
    }//GEN-LAST:event_txtVsgFunPesNomKeyReleased

    private void cboVsgFunPesCarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVsgFunPesCarItemStateChanged
        // TODO add your handling code here:
        consultaCargo();
    }//GEN-LAST:event_cboVsgFunPesCarItemStateChanged

    private void txtVsgFunIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVsgFunIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsgFunIdKeyReleased

    private void tblVsgFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVsgFunMouseClicked
        // TODO add your handling code here:
        consultarId();
    }//GEN-LAST:event_tblVsgFunMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVsgFunNom1;
    private javax.swing.JButton btnVsgFunRed;
    public static javax.swing.JComboBox<String> cboVsgFunCar;
    private javax.swing.JComboBox<String> cboVsgFunPesCar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblVsgFun;
    public static javax.swing.JTextField txtVsgFunCep;
    public static javax.swing.JTextField txtVsgFunDen;
    public static javax.swing.JTextField txtVsgFunDsa;
    public static javax.swing.JTextField txtVsgFunEnd;
    public static javax.swing.JTextField txtVsgFunFon;
    private javax.swing.JTextField txtVsgFunId;
    public static javax.swing.JTextField txtVsgFunNom;
    private javax.swing.JTextField txtVsgFunPesNom;
    // End of variables declaration//GEN-END:variables
}
